default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: dbname
  user: dbuser
  password:
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
